/*
 * 当前实现是一个页面只能存在一种语言
 * 实现为覆盖式的
 * var kslang={};
 * 如果需要多语言共存则应该这样
 * if( typeof langmanager=='undifined'){
 * 	langmanager={};
 * }
 * langmanager.cn={};
 * 
 * end by guxi 2011-07-18 PM
 * 
 */
var kslang={
	//公共
	comm_beforeunload:'离开此页面后,此页面信息将全部丢失,确定要离开此页面吗?',
	comm_notrecid:'正在初始化信息，请稍后重试',
	//聊天js
	oc_js_online_ok:'已成功为您接入人工接待，请输入您要咨询的问题',
	oc_js_shield:'对不起,您已被屏蔽,请联系网站管理员!',
	oc_js_addFavTitle:'快商通在线咨询',
	oc_js_hisHr:'以上是历史消息',
	oc_js_hisLoadHr:'查看上次对话',
	oc_js_dialogEnd:'您可以点击下面的按钮"保存"或"打印"保留本次对话记录.',
	oc_js_dialogEndMb:'您的本次沟通已结束，随时欢迎您再次咨询！',
	oc_js_valSucc:'非常感谢您的评价!',
	oc_js_saveFail:'您的浏览器有可能不支持该操作!',
	oc_js_saveTitle:'快商在线咨询聊天记录',
	oc_js_viewPic:'查看图片',
	oc_js_savePic:'保存图片',
	oc_js_dialogEndOpenNew:'对话已结束,请重新打开聊天窗口!',
	oc_js_dialogAlreadyEnd:'对话已结束!',
	oc_js_dialogAlreadyEndType:function(ec){return '对话已结束,结束类型['+ec+']!'},
	oc_js_dialogWait:'请等待客服人员应答',
	oc_js_dialogNewCurEnd:'由于您又建立了一个新对话,当前对话自动结束,请切换至新打开的聊天窗口继续咨询!',
	oc_js_chatIdNotEqu:'由于您又建立了一个新对话,该对话自动结束,请切换至新打开的聊天窗口继续咨询!',
	oc_js_csIsTyping:function(ec){return (ec||'客服')+' 正在打字给您,请稍候...'},
	oc_js_hasNewMsg:'***您有新的消息',
	oc_js_hasNotVal:'您还没有对本次服务进行评价',
	oc_js_youSay:'您说',
	oc_js_sysAlert:'【系统提示】',
	oc_js_robotAnswerTitle:'您是不是咨询下面的问题？',
	oc_js_fileSendFail:'文件发送失败!请检查文件是否超过1MB,或是文件类型不符合法!',
	oc_js_fileSendSucc:'文件发送成功!',
	oc_js_robotNoAnswer:'对不起，我还不会回答这个问题，请和我们的客服人员联系。',
	oc_js_delayConn:'秒后为您建立对话...',
	oc_js_failConn:function(ec){return '连接服务器出错,请重新打开聊天窗口重试 '+(ec?'['+ec+']':'')+'...'},
	//聊天窗口
	oc_toptitle_waitmsg:'正在呼叫在线的客服人员，请稍候',
	oc_toptitle_receive:function(ec){return (ec||'')+' 正在为您服务'},
	oc_online:'在线',
	oc_offline:'离线',
	oc_send:'发 送',
	oc_entersend:'按Enter发送',
	oc_ctrlentersend:'按Ctrl+Enter发送',
	oc_icon_onlineChat:'在线咨询',
	oc_icon_freeCall:'免费电话',
	oc_icon_leaveMsg:'在线留言',
	oc_icon_leaveMsg2us:'给我们留言',
	oc_icon_shortMsg:'短信留言',
	oc_icon_robotMsg:'自助服务',
	oc_no_customertochat:'没有客服人员在线,不能进行在线咨询!',
	oc_tranfer_notaccept:'客服忙，无法接待对话，正在呼叫其他客服，请稍候...',
	//评价
	oc_evaluate:'评价',
	oc_issatisfied:'您是否对此次服务感到满意',
	oc_description:'描述',
	oc_se_submit:'确定',
	oc_se_cancle:'取消',
	oc_evaluate_failed_trunhistory:'对话结束已超时，评价失败',
	//访客信息收集
	oc_vi_name:'姓名',
	oc_vi_mobile:'手机',
	oc_vi_phone:'电话',
	oc_vi_address:'地址',
	oc_vi_prefix:'收集的访客信息',
	//留言
	lm_username:'您的姓名',
	lm_phone:'电话号码',
	lm_qq:'QQ号码',
	lm_email:'电子邮件',
	lm_leaveTopic:'留言主题',
	lm_leaveContent:'留言内容',
	lm_btn_submit:'提交',
	lm_timeOut:'留言超时,请刷新页面后重新留言!',
	lm_submitSucc:'您的留言已经发送成功，我们会尽快处理，谢谢您的光临！',
	lm_errorCode:function(ec){return '留言失败,错误代码['+ec+']!'},
	lm_maxLength:function($1,$2,$3){return '【'+$1+'】不能大于'+$2+'字,当前字数为['+$3+']!'},
	lm_notEmpty:function($1){return '【'+$1+'】不能为空!'},
	lm_errorTitle:function($1){return '请输入正确的【'+$1+'】!'},
	
	//机器人
	oc_robot_title:'自助服务',
	oc_robot_shortMsg:'短信留言功能尚未完成,敬请期待...',
	oc_robot_entCard:'企业名片',
	oc_robot_entName:'企业名称',
	oc_robot_entPhone:'电话',
	oc_robot_entFax:'传真',
	oc_robot_entAddr:'地址',
	
	//编辑器
	oc_editor_blod_title:'粗体',
	oc_editor_italic_title:'斜体',
	oc_editor_underline_title:'下划线',
	oc_editor_forecolor_title:'字体颜色',
	oc_editor_fontsize_title:'字号',
	oc_editor_fontname_title:'字体',
	oc_editor_emotion_title:'表情',
	oc_editor_print_title:'打印',
	oc_editor_sendimg_title:'发送图片',
	oc_editor_sendfile_title:'发送文件',
	oc_editor_cutpic_title:'截图',
	oc_editor_msgsound_title:'声音',
	oc_editor_evaluate_title:'评价',
	oc_editor_clearwindow_title:'清除屏幕讯息',
	oc_editor_quickask_title:'快速提出您的问题',
	oc_editor_map_title:'查找该公司的地理位置',
	oc_editor_saverecord_title:'保存记录',
	oc_editor_translate_title:'翻译',
	oc_editor_fontpanel_title:'设置字体',
	oc_editor_wechat_title:'微信',
	oc_editor_blod_text:'粗体',
	oc_editor_italic_text:'斜体',
	oc_editor_underline_text:'下划线',
	oc_editor_forecolor_text:'字体颜色',
	oc_editor_fontsize_text:'字号',
	oc_editor_fontname_text:'字体',
	oc_editor_emotion_text:'表情',
	oc_editor_msgsound_text:'声音',
	oc_editor_print_text:'打印',
	oc_editor_sendfile_text:'文件',
	oc_editor_sendimg_text:'图片',
	oc_editor_cutpic_text:'截图',
	oc_editor_evaluate_text:'评价',
	oc_editor_clearwindow_text:'清屏',
	oc_editor_quickask_text:'快速提问',
	oc_editor_map_text:'地图',
	oc_editor_saverecord_text:'保存记录',
	oc_editor_translate_text:'翻译',
	oc_editor_fontpanel_text:'设置字体',
	oc_editor_wechat_text:'微信',
	
	oc_editor_selectFile:'选择文件',
	oc_editor_sendfile:'传送文件',
	oc_editor_sendfileBtn:'发送',
	oc_editor_tips:'提示',
	oc_editor_tipmsg:'最大允许传送的文件大小为1MB.',
	oc_editor_forlang:'源语言',
	oc_editor_tolang:'目标语言',
	oc_editor_usefun:'使用该功能',
	oc_lang_auto:'检测语言',
	
	oc_editor_clearwindow_confirm:'确定清除聊天记录吗?',
	oc_editor_default:'默认',
	oc_editor_alertStatus0:function($1){return '会话已停止,不能'+($1?eval('kslang.'+$1):kslang.oc_editor_usefun)},
	oc_editor_alertcutpic0:'没有与任何客服建立连接,不能截图!',
	oc_editor_alertcutpic1:'会话已停止,不能发送截图!',
	oc_editor_alertcutpic2:'非IE浏览器不支持截图!',
	oc_editor_alertcutpic3:'没有安装截图控件,请先下载截图控件!',
	oc_editor_alertcutpic4:'是否隐藏当前窗口?',
	oc_editor_alertcutpic5:'截图控件被第三方工具恶意破坏,请重新安装!',
	oc_editor_alertfile0:'会话已停止,不能发送文件!',
	oc_editor_alertfile1:'请先选择需要上传的文件!',
	oc_editor_alertfile2:'会话未建立,不能发送文件!',
	oc_editor_alertdrag0:'只能同时拖拽发送一个文件,请耐心等待...',
	oc_editor_alertdrag1:'只能同时拖拽发送一个文件...',
	oc_editor_alertdrag2:'您拖拽的文件类型不允许发送！',
	oc_editor_alertdrag3:'发送文件失败，您拖拽的文件不允许发送！',
	oc_editor_sendmsg0:'对话已结束，若还有问题，随时欢迎您再次咨询，祝您愉快，再见！',
	oc_editor_sendmsg1:'对话未建立成功,无法发送消息!',
	oc_editor_sendmsg2:'您发送的内容过多,请减少些内容后再发!',
	oc_editor_sendmsg3:'您发送信息太频繁了,过会儿再发吧!',
    oc_editor_sendmsg4:'您的IE版本过低，无法发送消息，请及时更新。',
	oc_editor_orderInfo:function(order){return '当前客服接待已满，您现在处于队列第<span style="color:blue;" id="ks_ordermsg_num">'+order+'</span>位，请稍等...'},
	oc_editor_orderLeave:'若您不想继续等待，请点击<span style="color:blue;cursor:pointer;" id="ks_ordermsg_num" onclick="ksOnlineChat.openLeaveWin()">留言</span>',

	oc_editor_vcanoanswer:function(robotName){return '成长虽易，完善不易，且行且珍惜。'+robotName+'会继续努力的！为了您的问题尽快解决，请咨询<a class="chatOnline" onclick="ksOnlineChat.gotoOnline()">人工客服</a>'},
	oc_editor_vcaenternum:'请输入序号或',
	oc_editor_vcaclickview:'点击问题查看答案',
	oc_editor_vcasatisfied:'满意',
	oc_editor_vcadissatisfied:'不满意',
	
	oc_vca_title:'智能机器人',
	oc_vca_nocustmer:'没有客服在线，我继续为您服务',
	oc_vca_24h:'24小时竭诚为您服务',
	oc_vca_tran2online:'正在为您转接人工客服',
	oc_vca_tofreephone:'是否进入免费电话拨打界面？您可以返回该页面继续咨询',
	oc_vca_rightTitle:'常见问题',
	oc_vca_valSucc:function(robotName){return '非常感谢您的评价，'+robotName+'会继续努力的！';},
	oc_vca_sizelimit:function(limit){return '仅支持图片发送，大小限'+limit+'Mb'},
	oc_vca_picoversize:function(fileNum){return '图片不能超过'+fileNum+'Mb，请用前置摄像头拍摄'},
	oc_vca_uploading:'图片上传中，请稍候...',
	oc_vca_resendimg:'上次图片发送失败，是否重新发送？',
	oc_vca_supportimg:'仅支持格式',
	oc_vca_needuploadimg:'是否上传图片',
	oc_vca_sendfail:'图片发送失败',
	
	oc_vca_hotline:'咨询热线',
	oc_vca_callme:'您也可以电话咨询我',
	oc_vca_voice:'语音',
	oc_vca_hold:'按住说话',
	oc_vca_loose:'松开结束',
	oc_vca_authorized:'您已成功授权，可以进行语音交流了',
	oc_vca_recordshort:'录音时间太短',
	oc_vca_voicesending:'语音发送中...',
	
	oc_evaluate_noscore:'请点击进行评分',
	oc_editor_alertevaluate0:'没有与任何客服建立连接,不能进行评价!',
	oc_editor_alertevaluate1:'会话已停止,不能进行评价!',
	
	oc_editor_order_web_title:'排队等待中……',
	oc_editor_order_web_msginfo:'<div class="kschatwindowstandard_line_up_head">很抱歉，当前客服已达到接待上限，请您耐心等候，我们很快将会为您服务，谢谢。</div><h2>当前排队人数</h2>',
	oc_editor_orderLeave_web:'<p>如果来不及，您可以</p><div class="kschatwindowstandard_line_up_btn" onclick="ksOnlineChat.openLeaveWin()">留言</div>',

	oc_chooseGroup_title:'选择咨询分组',
	oc_editor_shieldWords:function(ec){return '字段【'+ec+'】含有敏感词，请重新输入。'}
	};