//document.writeln("<script language=\"javascript\" src=\"http://style.caiwuchina.com/tg/js/jquery-1.9.1.min.js\"></script>");
//document.writeln("<script language=\"javascript\" src=\"http://style.caiwuchina.com/tg/zz/showzz.js\"></script>");
document.writeln("<script>");
document.writeln("var host = window.location.host;");
document.writeln("var bottomstr = \"\";");
document.writeln("if (host.indexOf(\"caiwuchina.com\")>-1 ){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华信息技术有限公司 鲁ICP备15005125号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"tg3.88caiwu.com\")>-1 || host.indexOf(\"tg4.88caiwu.com\")>-1){ ");
document.writeln("bottomstr  = \"  \";");
document.writeln("}else if (host.indexOf(\"88caiwu.com.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 滕州市宏忠商贸有限公司 客服电话：0632-83210225\";");
document.writeln("}else if (host.indexOf(\"88caiwu.com\")>-1 ){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华广告传媒有限公司 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"88caiwu.net\")>-1 ){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 攀枝花山人投资管理有限公司  客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"88caiwu.cn\")>-1){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 南昌市博远品牌管理有限公司 通讯地址：南昌市东湖区南京西路552号怡景阁8栋A单元201室 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"80900010.com\")>-1 ){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 深圳君林企业财务代理有限公司  客服电话：0755-58784513\";");
document.writeln("}else if (host.indexOf(\"caiwuzhijia.cn\")>-1 || host.indexOf(\"0531dljz.com\")>-1){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家 ALL RIGHTS RESERVED<br />Powered by 济南宝华企业管理咨询有限公司  客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"caiwuzhijia.cc\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 朔州市佳原工贸有限公司 朔州开发区大新一路 客服电话：400-000-1718 0349-95875247\";");
//document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华信息技术有限公司  2015 鲁ICP备15005125号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"haiproduct.com\")>-1){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 苏州百裕瑞贸易有限公司 客服电话：400-000-1718\";");
//document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华信息技术有限公司  2015 鲁ICP备15005125号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"caiwuzhijia.com.cn\")>-1 || host.indexOf(\"caiwuzhijia.net\")>-1){ ");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华信息技术有限公司  2015 鲁ICP备15005125号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"0531jt.com\")>-1 || host.indexOf(\"jintuogl.com\")>-1 || host.indexOf(\"jintuoqy.com\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 济南金拓企业管理咨询有限公司 鲁ICP备15017895号  客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"0531jb.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 济南金宝企业管理咨询有限公司 鲁ICP备15022640号-1 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"zc021.com\")>-1 || host.indexOf(\"zc021.cn\")>-1 || host.indexOf(\"zc021.net\")>-1){ ");
document.writeln("bottomstr  = \"<a href='http://www.miitbeian.gov.cn' style='text-decoration: none;color: rgba(158, 153, 153, 0.4);'>Powered by 上海皇吉贸易有限公司 沪ICP备16020254号-1 </a>\";");
document.writeln("}else if (host.indexOf(\"chengxinzx.com\")>-1 || host.indexOf(\"wmzszx.com\")>-1){ ");
document.writeln("bottomstr  = \"<a href='http://www.miitbeian.gov.cn' style='text-decoration: none;color: rgba(158, 153, 153, 0.4);'>Powered by 上海皇吉贸易有限公司 沪ICP备16020254号-2 </a>客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"021ccm.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 上海君宜文化传播有限公司  沪ICP备16025991号\";");
document.writeln("}else if (host.indexOf(\"home3.021lilu.com\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 上海松雷企业登记代理事务所  沪ICP备16030565号-1\";");
document.writeln("}else if (host.indexOf(\"021lilu.com\")>-1 || host.indexOf(\"021lilu.cn\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 上海黎录企业管理咨询有限公司  沪ICP备16030565号-1\";");
document.writeln("}else if (host.indexOf(\"0531jzb.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 济南金账本企业咨询管理有限公司 鲁ICP备14009752号-1 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"zzxhao.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：济南永东网络科技有限公司 鲁ICP备17012804号-1 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"shzhekuo\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 上海哲阔网络信息技术有限公司 沪ICP备16030994号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"551647.top\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 邯郸开发区乾鼎商贸有限公司 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"zwxs1596666pp.top\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：北京丙至商贸有限公司\";");
document.writeln("}else if (host.indexOf(\"szsyz365.org.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：北京时智时悦科技有限公司\";");
document.writeln("}else if (host.indexOf(\"zhuce.wrzx168.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：天津文瑞企业管理咨询有限公司\";");
document.writeln("}else if (host.indexOf(\"xinlearn.com\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：林州市广益商贸有限公司\";");
document.writeln("}else if (host.indexOf(\"6w9o.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：台恩耐腐蚀泵制造（上海）有限公司\";");
document.writeln("}else if (host.indexOf(\"6k9i.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：上海中美自控阀门有限公司\";");
document.writeln("}else if (host.indexOf(\"xinjie222.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：安徽省新界科技有限公司\";");
document.writeln("}else if (host.indexOf(\"xinjie222.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：安徽省新界科技有限公司\";");
document.writeln("}else if (host.indexOf(\"hzsblmy23.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 版权所有：河南漯阜铁路实业有限公司\";");

document.writeln("}else if (host.indexOf(\"cxsearch.cn\")>-1 ){ ");
document.writeln("bottomstr  = \"Powered by 慈溪市创鼎网络科技有限公司\";");

document.writeln("}else if (host.indexOf(\"xyyzt.cn\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 潍坊信达代理记账有限公司\";");

document.writeln("}else if (host.indexOf(\"poterpt.top\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 化州市清鼻堂健康咨询有限公司\";");
document.writeln("$(\".comname\").html(\"化州市清鼻堂健康咨询有限公司\");");
document.writeln("}else if (host.indexOf(\"shlanou.top\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 徐闻县安可投资信息咨询有限公司\";");
document.writeln("$(\".comname\").html(\"徐闻县安可投资信息咨询有限公司\");");

document.writeln("}else if (host.indexOf(\"cheryqq.cn\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 平凉棋翔商贸有限公司\";");
document.writeln("$(\".comname\").html(\"平凉棋翔商贸有限公司\");");

document.writeln("}else if (host.indexOf(\"cheryqq.cn\")>-1){ ");
document.writeln("bottomstr  = \"Powered by 平凉棋翔商贸有限公司\";");
document.writeln("$(\".comname\").html(\"平凉棋翔商贸有限公司\");");
document.writeln("}else if (host.indexOf(\"zhcue.kqdjt.cn\")>-1 ){ ");
document.writeln("bottomstr  = \" \";");
document.writeln("}else if (host.indexOf(\"zhuce1.ggbjt.cn\")>-1 ){ ");
document.writeln("bottomstr  = \" \";");
document.writeln("}else if (host.indexOf(\"bh0531.com\")>-1 ){ ");
//document.writeln("bottomstr  = \"Powered by 苏州金笔尖企业管理咨询有限公司 客服电话：400-000-1718\";");
document.writeln("bottomstr  = \"COPYRIGHT @ 2002-2018 财务之家旗下网站 ALL RIGHTS RESERVED<br />Powered by 济南宝华信息技术有限公司  2015 鲁ICP备15005125号 客服电话：400-000-1718\";");
document.writeln("}else if (host.indexOf(\"guozuxie.com\")>-1 ){ ");
document.writeln("bottomstr  = \"  \";");
document.writeln("}");
document.writeln("if(bottomstr != \"\"){");
document.writeln("$(\".foot_bottom_left\").html(bottomstr);");
document.writeln("$(\".foot_bottom_left\").css(\"color\", \"rgba(158, 153, 153, 0.4)\");");
document.writeln("}");
document.writeln("</script>");
document.writeln("<div style=\" position:fixed; z-index:9999999; left:31%; top:23%;cursor:pointer;\" id=MainSwt>");
document.writeln("    <a onclick=\"openZoosUrl(\'chatwin\');LR_HideInvite();return false;\">");
document.writeln("    ");
document.writeln("    <img src=\"http://style.caiwuchina.com/tg/swt/img/invitebg2.jpg\" >");
document.writeln("    <a onclick=\"closeWin();LR_RefuseChat();return false;\" alt=\"关闭\" style=\" position:absolute; top:4%;right:1%; font-size:20px; color:#FFF; font-weight:bold;\">");
document.writeln("    <img src=\"http://style.caiwuchina.com/tg/swt/img/close.png\" ></a>");
document.writeln("    </a>");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln("   </div>");
document.writeln("   <script>");
document.writeln("   ");
document.writeln("    function closeWin(){");
document.writeln("		   document.getElementById(\"MainSwt\").style.display=\"none\";");
document.writeln("		  }");
document.writeln("   </script>");
function action_swt(){
var ele= document.getElementById("LRdiv1");
	
	if(ele){
		 document.getElementById("LRdiv1").style.display="none";
	}
}